import type { Metadata } from "next";
import { Inria_Serif } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/navBar/Header";

const inriaSerif = Inria_Serif({
  variable: "--font-inria-serif",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Jesus Canales Abogado Lima",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inriaSerif.variable}  antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
